name = "tiago"
author = "eu"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0f4bef1a38e09b0fe1cd35e20f4ec34521e8a5154495f2e2e03a4c0bf1ea262"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
