name = "tiago"
author = "eu"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3de640c3a13e471c2a2bae402cbe30756e857c01d417b11a3018129941dcb837"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
