name = "tiago"
author = "eu"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dfd22183aa361e9dce7c393ef6920e454805ac7c8ad23bb86231c49cb595848"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
